# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set([('card_code', 'company')]),
        ),
    ]
