# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom User'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userpic',
            field=models.ImageField(blank=True, null=True, upload_to='userpic/'),
        ),
    ]
