# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('cards', '0002_auto_20160622_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user_ptr',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('C', 'Company'), ('U', 'User')], default='U', max_length=2),
        ),
        migrations.AlterField(
            model_name='card',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='cards.CustomUser'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='cards.CustomUser'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
